deployment:
  tasks:
    # move todas as pastas onde está o arquivo .cpanel para /home1/rifad375/sitesdriversoft.com.br/Gerenciamento-de-Alunos/
    - export DEPLOYPATH=/home1/rifad375/sitesdriversoft.com.br/Gerenciamento-de-Alunos/
    - /bin/cp -R * $DEPLOYPATH


